export const COMPARE_USER = 'COMPARE_USER';
export const COMPARE_USER_SUCCESS = 'COMPARE_USER_SUCCESS';
export const COMPARE_USER_FAILED = 'COMPARE_USER_FAILED';

export const LOGIN_TO_GET_TOKEN = 'LOGIN_TO_GET_TOKEN';
export const LOGIN_TO_GET_TOKEN_SUCCESS = 'LOGIN_TO_GET_TOKEN_SUCCESS';
export const LOGIN_TO_GET_TOKEN_FAILED = 'LOGIN_TO_GET_TOKEN_FAILED';
