export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';

export const FETCH_GENERAL_BANNER = 'FETCH_GENERAL_BANNER';
export const FETCH_GENERAL_BANNER_SUCCESS = 'FETCH_GENERAL_BANNER_SUCCESS';
export const FETCH_GENERAL_BANNER_FAILD = 'FETCH_GENERAL_BANNER_FAILD';

export const FETCH_GENERAL_INFORMATION = 'FETCH_GENERAL_INFORMATION';
export const FETCH_GENERAL_INFORMATION_SUCCESS = 'FETCH_GENERAL_INFORMATION_SUCCESS';
export const FETCH_GENERAL_INFORMATION_FAILED = 'FETCH_GENERAL_INFORMATION_FAILED';
